# Generated by Django 3.2.4 on 2021-06-09 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notification_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 23, 26, 57, 323141)),
        ),
    ]
